### ISSUE TITLE
NIie odpala

### ISSUE THREAD

**Issue by Schaffn** [dani3l0/librusik#2]
```
C:\Users\x\Desktop\librusik>python librusik.py
Traceback (most recent call last):
  File "C:\Users\x\Desktop\librusik\librusik.py", line 18, in <module>
    from lib.utils import *
  File "C:\Users\x\Desktop\librusik\lib\utils.py", line 112, in <module>
    statvfs = os.statvfs(".")
AttributeError: module 'os' has no attribute 'statvfs'
```
```
C:\Users\x\Desktop\librusik>python --version
Python 3.10.6
```
https://docs.python.org/3.10/library/os.html?highlight=statvfs#os.statvfs
Ta funkcja jest dostępna tylko na "unixowych" os, a z tego co mi wiadomo ma być to cross platform aplikacja.

**Comment by dani3l0** [comment]
Hmm, rzeczywiście. Funkcja służy tylko do podawania [raczej zbędnej] informacji o rozmiarze dysku w Panelu.
Nie mam za dużo do czynienia z Windowsem :disappointed: więc i taki bug się zakradł, ale to do naprawienia.

Dzięki za informację!

**Comment by dani3l0** [comment]
Chyba już odpala, to zamykam
