### ISSUE TITLE
Konsola printuje złe ip 

### ISSUE THREAD

**Issue by Schaffn** [dani3l0/librusik#3]
![image](https://user-images.githubusercontent.com/81300193/227792789-635698aa-d562-40e5-b070-0eabdf1ebf28.png)
https://superuser.com/questions/949428/whats-the-difference-between-127-0-0-1-and-0-0-0-0

Konsola printuje złe ip, nie jest to może jakiś problem dla kogoś kto się "zna" jednak typowy anon nie dałby sobie rady.

os: Windows 10
python: 3.10

**Comment by dani3l0** [comment]
Tu się nie do końca zgadza, bo jak ustawimy adres na 127.0.0.1 to apka będzie dostępna tylko na kompie na którym działa (nie będzie dostępna po LANie)

**Comment by Schaffn** [comment]
Prawda, przydałby się jakiś config file aby ustawiać widoczność aplikacji bądź port

**Comment by dani3l0** [comment]
ip/port powinny być już konfigurowalne
co do anonów to nie wiem czy taki przeciętniak byłby w stanie ustawić pythona i zainstalować moduły, większe szanse miałby z Librusikiem upakowanym w jakimś Electronie itp

**Comment by dani3l0** [comment]
Ref #5
