### ISSUE TITLE
Teacher free days traceback

### ISSUE THREAD

**Issue by Narwhall85** [dani3l0/librusik#6]
Przy próbie odpalenia nieobecności nauczycieli, wyrzuca błąd:

Traceback (most recent call last):
File "C:\Users\czerw\Downloads\librusik-stable\librusik-stable\librusik.py", line 881, in teacherfreedays
result = (await librus.get_teacher_free_days())[::-1]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\czerw\Downloads\librusik-stable\librusik-stable\lib\api\librus.py", line 208, in get_teacher_free_days
i["Teacher"] = teachers[i["Teacher"]["Id"]]
^^^^^^^^^^^^^^^^^^^^
KeyError: 2020133

![Zrzut ekranu 2023-11-28 101851](https://github.com/dani3l0/librusik/assets/47447716/2cf463a5-878e-479d-a924-719ee79d2d86)

**Comment by dani3l0** [comment]
Owow, sorry nie zauważyłem issua :(

Wygląda mi jakby librusik dostał id nieistniejącego nauczyciela? Nie mam dostępu do librusa już, ale możemy spróbować klasycznie wsadzić ten kawałek kodu w `try`/`catch` i zobaczyć czy pomoże

**Comment by dani3l0** [comment]
_git chyba wyłapuje słowo 'fix' w commicie_

Daj znać czy partyzancki fix pomógł xD

**Comment by Narwhall85** [comment]
Jakimś cudem to naprawiłem, że jak jest to ID nauczyciela to ignoruje i no

teraz sie staram jak zrobić, żeby ogłoszenia zrobić
topornie idzie ale próbuje

**Comment by Narwhall85** [comment]
Zaraz spróbuje tego fixa czy działa

**Comment by dani3l0** [comment]
> teraz sie staram jak zrobić, żeby ogłoszenia zrobić
> topornie idzie ale próbuje

W toolsach masz `dump_full_api.py`, może okazać się przydatne xd
